version: 2.1
jobs:
  build:
    working_directory: ~/quality-control
    docker: 
      - image: circleci/python:3.7.7 
    steps:
      - checkout
      - run:
          command:
            pip install -r requirements.txt
      - run:
          command:
            python run_quality_checks.py

workflows:
  main:
    jobs:
      - build
